const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const OUT = path.join(__dirname, "../public/bravo-report.pdf");
const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
doc.pipe(fs.createWriteStream(OUT));

const BRAND  = "#7C3AED";
const ACCENT = "#EC4899";
const GREEN  = "#059669";
const RED    = "#DC2626";
const AMBER  = "#D97706";
const SLATE  = "#1E293B";
const MUTED  = "#64748B";
const LIGHT  = "#F1F5F9";
const WHITE  = "#FFFFFF";
const BORDER = "#E2E8F0";
const W = 495;

// ── helpers ──────────────────────────────────────────────────────────────────

function rule(y, color = BORDER, lw = 0.5) {
  doc.save().strokeColor(color).lineWidth(lw).moveTo(50, y).lineTo(545, y).stroke().restore();
}

function sectionTitle(text, y) {
  doc.save().rect(50, y, 4, 18).fill(BRAND)
    .fontSize(13).fillColor(SLATE).font("Helvetica-Bold").text(text, 62, y + 1).restore();
  return y + 30;
}

function progressBar(x, y, w, pct, color) {
  doc.save()
    .roundedRect(x, y, w, 6, 3).fill(LIGHT)
    .roundedRect(x, y, Math.max(4, w * Math.min(pct, 1)), 6, 3).fill(color)
    .restore();
}

function statusColor(s) {
  return s === "ON TRACK" ? GREEN : s === "AT RISK" ? AMBER : RED;
}

function statusBadge(x, y, text) {
  const col = statusColor(text);
  const pw = doc.widthOfString(text, { fontSize: 7 }) + 10;
  doc.save().roundedRect(x, y, pw, 13, 4).fill(col + "22")
    .fontSize(7).fillColor(col).font("Helvetica-Bold")
    .text(text, x + 5, y + 3, { lineBreak: false }).restore();
}

function table(headers, rows, x, y, colW, rowH = 19) {
  const totalW = colW.reduce((a, b) => a + b, 0);
  // header
  doc.save().rect(x, y, totalW, rowH).fill(BRAND).restore();
  let cx = x;
  headers.forEach((h, i) => {
    doc.save().fontSize(7.5).fillColor(WHITE).font("Helvetica-Bold")
      .text(h, cx + 5, y + 6, { width: colW[i] - 8, lineBreak: false }).restore();
    cx += colW[i];
  });
  y += rowH;
  rows.forEach((row, ri) => {
    doc.save().rect(x, y, totalW, rowH).fill(ri % 2 === 0 ? WHITE : LIGHT).restore();
    cx = x;
    row.forEach((cell, ci) => {
      const s = String(cell);
      const isStatus = ["ON TRACK","AT RISK","OFF TRACK","CRITICAL","HIGH","MEDIUM","LOW"].includes(s);
      if (isStatus) {
        statusBadge(cx + 4, y + 3, s);
      } else {
        doc.save().fontSize(7.5).fillColor(SLATE).font("Helvetica")
          .text(s, cx + 5, y + 6, { width: colW[ci] - 8, lineBreak: false }).restore();
      }
      cx += colW[ci];
    });
    doc.save().strokeColor(BORDER).lineWidth(0.3)
      .moveTo(x, y + rowH).lineTo(x + totalW, y + rowH).stroke().restore();
    y += rowH;
  });
  return y;
}

function pageHeader(title, subtitle) {
  doc.save().rect(50, 40, W, 2).fill(BRAND).restore();
  doc.save().fontSize(18).fillColor(SLATE).font("Helvetica-Bold").text(title, 50, 52).restore();
  if (subtitle) doc.save().fontSize(8).fillColor(MUTED).font("Helvetica").text(subtitle, 50, 74).restore();
  rule(86);
  return 104;
}

// ══════════════════════════════════════════════════════════════════════════════
// PAGE 1 — COVER
// ══════════════════════════════════════════════════════════════════════════════
doc.save().rect(0, 0, 595, 842).fill(SLATE).restore();
doc.save().rect(0, 0, 595, 6).fill(BRAND).restore();
doc.save().rect(0, 6, 595, 3).fill(ACCENT).restore();

doc.save().fontSize(28).fillColor(WHITE).font("Helvetica-Bold").text("BRAVO", 50, 120, { lineBreak: false }).restore();
doc.save().fontSize(28).fillColor(BRAND).font("Helvetica-Bold")
  .text(" AI", 50 + doc.widthOfString("BRAVO", { fontSize: 28 }), 120, { lineBreak: false }).restore();
doc.save().fontSize(11).fillColor("#94A3B8").font("Helvetica").text("Workforce Intelligence Platform", 50, 156).restore();

doc.save().fontSize(36).fillColor(WHITE).font("Helvetica-Bold")
  .text("Executive Operations\nIntelligence Report", 50, 220, { width: 420 }).restore();

doc.save().strokeColor(BRAND).lineWidth(2).moveTo(50, 318).lineTo(200, 318).stroke().restore();

const meta = [
  ["Report Period",  "May 2026 · Q2"],
  ["Coverage",       "5 Branches · 7 Departments"],
  ["Generated by",   "Bravo AI Engine v2.4"],
  ["Classification", "Confidential — Manager Use Only"],
];
meta.forEach(([k, v], i) => {
  doc.save().fontSize(8).fillColor("#94A3B8").font("Helvetica").text(k.toUpperCase(), 50, 338 + i * 28).restore();
  doc.save().fontSize(11).fillColor(WHITE).font("Helvetica-Bold").text(v, 50, 351 + i * 28).restore();
});

const coverStats = [
  { label: "Avg Productivity", value: "74/100" },
  { label: "Waste Reduced",    value: "−18.4%" },
  { label: "FIFO Compliance",  value: "87.2%" },
  { label: "Spoilage Rate",    value: "6.1%" },
];
coverStats.forEach((s, i) => {
  const bx = 50 + i * 115;
  doc.save().roundedRect(bx, 560, 108, 60, 8).fill("#FFFFFF11").restore();
  doc.save().fontSize(20).fillColor(WHITE).font("Helvetica-Bold").text(s.value, bx + 10, 576).restore();
  doc.save().fontSize(7.5).fillColor("#94A3B8").font("Helvetica").text(s.label, bx + 10, 600).restore();
});

// ══════════════════════════════════════════════════════════════════════════════
// PAGE 2 — TRANSITION (minimal, premium)
// ══════════════════════════════════════════════════════════════════════════════
doc.addPage();
doc.save().rect(0, 0, 595, 842).fill("#FAFBFF").restore();
doc.save().rect(0, 0, 595, 4).fill(BRAND).restore();

// Centered content
const centerX = 297;

// Main title
doc.save().fontSize(26).fillColor(SLATE).font("Helvetica-Bold")
  .text("Operational Intelligence Report", 50, 376, { align: "center", width: W }).restore();

// Thin rule
doc.save().strokeColor(BRAND).lineWidth(1.5).moveTo(197, 414).lineTo(398, 414).stroke().restore();

// Subtitle
doc.save().fontSize(10).fillColor(MUTED).font("Helvetica")
  .text(
    "AI-generated operational insights for waste reduction, FIFO optimisation,\nand workforce productivity across Bravo supermarket branches.",
    50, 428, { align: "center", width: W, lineGap: 4 }
  ).restore();

// Bottom confidential block
doc.save().roundedRect(147, 700, 300, 72, 8).fill(SLATE).restore();
doc.save().fontSize(11).fillColor(WHITE).font("Helvetica-Bold")
  .text("Confidential", 147, 716, { align: "center", width: 300 }).restore();
doc.save().fontSize(9).fillColor("#94A3B8").font("Helvetica")
  .text("Internal Use Only", 147, 734, { align: "center", width: 300 }).restore();
doc.save().fontSize(8).fillColor(BRAND).font("Helvetica-Bold")
  .text("Bravo AI Engine v2.4", 147, 750, { align: "center", width: 300 }).restore();

// ══════════════════════════════════════════════════════════════════════════════
// PAGE 3 — EXECUTIVE SUMMARY
// ══════════════════════════════════════════════════════════════════════════════
doc.addPage();
let y = pageHeader("Executive Summary", "Chain-wide performance overview · May 2026");

// Narrative
doc.save().fontSize(8.5).fillColor(SLATE).font("Helvetica")
  .text(
    "The Bravo AI engine analysed 2,400+ daily operational data points across spoilage events, inventory " +
    "rotations, FIFO scans, and task completion logs. Chain productivity improved 4.3 pts quarter-on-quarter. " +
    "Waste reduction initiatives delivered a net saving of ₼38,400 this quarter, with ₼153,600 projected " +
    "annualised savings at current trajectory. FIFO non-compliance remains the lead risk in Fish and Dairy.",
    50, y, { width: W, lineGap: 2 }
  ).restore();
y += 62;

// Stat boxes
const statBoxes = [
  { label: "Chain Productivity", value: "74.2", unit: "/100",  delta: "+4.3 pts QoQ",    color: BRAND },
  { label: "Waste Reduction",    value: "18.4", unit: "%",     delta: "+6.1% vs Q1",      color: GREEN },
  { label: "FIFO Compliance",    value: "87.2", unit: "%",     delta: "↑ from 81.4%",     color: BRAND },
  { label: "Spoilage Rate",      value: "6.1",  unit: "%",     delta: "↓ from 8.7% Q1",   color: GREEN },
];
const bw = (W - 12) / 4;
statBoxes.forEach((s, i) => {
  const bx = 50 + i * (bw + 4);
  doc.save().roundedRect(bx, y, bw, 68, 6).fill(LIGHT).restore();
  doc.save().rect(bx, y, 3, 68).fill(s.color).restore();
  doc.save().fontSize(7).fillColor(MUTED).font("Helvetica").text(s.label, bx + 10, y + 9).restore();
  doc.save().fontSize(22).fillColor(SLATE).font("Helvetica-Bold").text(s.value, bx + 10, y + 24, { lineBreak: false }).restore();
  const vw = doc.widthOfString(s.value, { fontSize: 22 });
  doc.save().fontSize(8.5).fillColor(MUTED).font("Helvetica").text(s.unit, bx + 13 + vw, y + 32, { lineBreak: false }).restore();
  doc.save().fontSize(7.5).fillColor(GREEN).font("Helvetica-Bold").text(s.delta, bx + 10, y + 51).restore();
});
y += 84;

// AI insights box
doc.save().roundedRect(50, y, W, 70, 6).fill("#EDE9FE").restore();
doc.save().rect(50, y, 4, 70).fill(BRAND).restore();
doc.save().fontSize(8).fillColor(BRAND).font("Helvetica-Bold").text("✦  AI ENGINE KEY FINDINGS", 62, y + 10).restore();
const findings = [
  "• Branch 04 Meat dept is top performer (91/100) — recommend cross-branch knowledge transfer.",
  "• Fish departments: 3 of 5 branches below 90% cold-chain compliance threshold.",
  "• Bakery waste cut 23% after AI daily mission system deployment — strongest gain this quarter.",
  "• Inventory FIFO improved from 74% → 86% following targeted morning-rotation missions.",
];
doc.save().fontSize(7.5).fillColor(SLATE).font("Helvetica")
  .text(findings.join("\n"), 62, y + 24, { width: W - 22, lineGap: 2 }).restore();
y += 86;

// Branch table
y = sectionTitle("Branch Performance Overview", y);
y = table(
  ["Branch", "Location", "Productivity", "FIFO", "Waste", "Q2 Savings", "Status"],
  [
    ["Branch 01", "Baku Central",       "76.4", "88%", "5.8%", "₼8,200",  "ON TRACK"],
    ["Branch 04", "Baku North",         "81.2", "91%", "4.2%", "₼11,400", "ON TRACK"],
    ["Branch 09", "Sumqayit Main",      "69.8", "83%", "7.9%", "₼5,600",  "AT RISK"],
    ["Branch 12", "Ganja Central",      "72.1", "86%", "6.8%", "₼7,100",  "AT RISK"],
    ["Branch 15", "Mingachevir Market", "71.5", "84%", "7.1%", "₼6,900",  "AT RISK"],
  ],
  50, y, [72, 130, 66, 48, 52, 72, 65]
);

y += 20;

// Financial snapshot
doc.save().roundedRect(50, y, W, 44, 6).fill(SLATE).restore();
doc.save().fontSize(8).fillColor("#94A3B8").font("Helvetica")
  .text("TOTAL Q2 WASTE COST", 66, y + 10).restore();
doc.save().fontSize(18).fillColor(WHITE).font("Helvetica-Bold")
  .text("₼18,300", 66, y + 22, { lineBreak: false }).restore();
doc.save().fontSize(8).fillColor("#94A3B8").font("Helvetica")
  .text("SAVINGS vs Q1", 230, y + 10).restore();
doc.save().fontSize(18).fillColor(GREEN).font("Helvetica-Bold")
  .text("₼4,100  (−18.3%)", 230, y + 22, { lineBreak: false }).restore();
doc.save().fontSize(8).fillColor("#94A3B8").font("Helvetica")
  .text("ANNUALISED PROJECTION", 420, y + 10).restore();
doc.save().fontSize(18).fillColor(ACCENT).font("Helvetica-Bold")
  .text("₼153,600", 420, y + 22, { lineBreak: false }).restore();

// ══════════════════════════════════════════════════════════════════════════════
// PAGE 4 — KPI ANALYSIS
// ══════════════════════════════════════════════════════════════════════════════
doc.addPage();
y = pageHeader("Department KPI Analysis", "AI-generated KPIs · Branch 01 deep-dive + chain achievement");

y = sectionTitle("KPI Status — Branch 01 (All Departments)", y);
y = table(
  ["Dept", "KPI Description", "Current", "Target", "Status"],
  [
    ["Meat",       "Reduce expired quantity by 15%",      "82%", "90%", "AT RISK"],
    ["Meat",       "Achieve 92% FIFO compliance",          "94%", "92%", "ON TRACK"],
    ["Fish",       "Cold-chain compliance above 95%",      "86%", "95%", "AT RISK"],
    ["Fish",       "Cut spoilage rate below 6%",           "71%", "94%", "OFF TRACK"],
    ["Fish",       "Morning freshness check by 9 AM",      "92%", "90%", "ON TRACK"],
    ["Bakery",     "Reduce end-of-day bread waste by 20%", "90%", "90%", "ON TRACK"],
    ["Bakery",     "Same-day sell-through above 88%",      "93%", "92%", "ON TRACK"],
    ["Dairy",      "Cold storage temp compliance",         "84%", "90%", "AT RISK"],
    ["Dairy",      "Near-expiry clearance rate",           "67%", "90%", "OFF TRACK"],
    ["Vegetables", "Daily freshness inspection 100%",      "95%", "90%", "ON TRACK"],
    ["Shelf",      "Shelf availability above 96%",         "91%", "96%", "AT RISK"],
    ["Inventory",  "Stock accuracy above 98%",             "96%", "94%", "ON TRACK"],
  ],
  50, y, [74, 210, 58, 55, 68], 18
);

y += 18;
y = sectionTitle("KPI Achievement Rate by Department (Chain-wide)", y);

const deptAch = [
  { dept: "Meat",       rate: 0.71, score: 79 },
  { dept: "Fish",       rate: 0.48, score: 62 },
  { dept: "Bakery",     rate: 0.87, score: 84 },
  { dept: "Dairy",      rate: 0.52, score: 66 },
  { dept: "Vegetables", rate: 0.74, score: 76 },
  { dept: "Shelf",      rate: 0.80, score: 81 },
  { dept: "Inventory",  rate: 0.68, score: 74 },
];
deptAch.forEach((d) => {
  const col = d.rate >= 0.75 ? GREEN : d.rate >= 0.55 ? AMBER : RED;
  doc.save().fontSize(8.5).fillColor(SLATE).font("Helvetica-Bold").text(d.dept, 50, y).restore();
  progressBar(140, y + 2, 210, d.rate, col);
  doc.save().fontSize(8).fillColor(MUTED).font("Helvetica")
    .text(`${Math.round(d.rate * 100)}% KPIs on track`, 358, y).restore();
  doc.save().fontSize(8).fillColor(col).font("Helvetica-Bold")
    .text(`${d.score}/100`, 460, y).restore();
  y += 20;
});

// ══════════════════════════════════════════════════════════════════════════════
// PAGE 5 — WASTE INTELLIGENCE
// ══════════════════════════════════════════════════════════════════════════════
doc.addPage();
y = pageHeader("Waste Intelligence Report", "AI Waste Risk Detection · Spoilage & financial impact analysis");

y = sectionTitle("Waste Rate Matrix — by Department & Branch (%)", y);
y = table(
  ["Department", "BR-01", "BR-04", "BR-09", "BR-12", "BR-15", "Chain Avg"],
  [
    ["Meat",       "4.2", "5.1", "7.8", "6.3", "6.9", "6.1"],
    ["Fish",       "9.0", "6.4", "11.2","8.7", "9.8", "9.0"],
    ["Bakery",     "6.0", "4.8", "8.3", "7.1", "7.4", "6.7"],
    ["Dairy",      "7.5", "5.9", "9.1", "8.0", "8.3", "7.8"],
    ["Vegetables", "8.2", "6.7", "10.5","9.2", "9.6", "8.8"],
    ["Shelf",      "1.8", "1.4", "2.9", "2.3", "2.5", "2.2"],
    ["Inventory",  "3.1", "2.6", "4.7", "3.9", "4.1", "3.7"],
  ],
  50, y, [110, 60, 60, 60, 60, 60, 70]
);

y += 16;
y = sectionTitle("High-Priority Spoilage Events — May 2026", y);
y = table(
  ["Date", "Branch", "Dept", "Event", "Loss ₼", "Severity"],
  [
    ["2026-05-02", "BR-09", "Fish",    "Cold-chain failure 4h",   "₼340", "CRITICAL"],
    ["2026-05-05", "BR-01", "Dairy",   "Near-expiry not rotated", "₼180", "HIGH"],
    ["2026-05-07", "BR-12", "Vegetables","Delivery delay — heat", "₼220", "HIGH"],
    ["2026-05-09", "BR-15", "Fish",    "Morning check missed",    "₼150", "HIGH"],
    ["2026-05-11", "BR-09", "Meat",    "FIFO skip — back stock",  "₼260", "CRITICAL"],
    ["2026-05-13", "BR-01", "Fish",    "Cold-chain < 95% for 3h", "₼190", "HIGH"],
  ],
  50, y, [76, 54, 74, 166, 58, 67], 18
);

y += 16;
y = sectionTitle("Financial Impact Summary", y);
const finRows = [
  ["Q1 2026 Total Waste Cost",     "₼22,400"],
  ["Q2 2026 (to date) Waste Cost", "₼18,300"],
  ["Savings vs Q1",                "₼4,100  (−18.3%)"],
  ["Projected Q2 Full Quarter",    "₼19,800"],
  ["Annualised Savings (trend)",   "₼153,600"],
];
finRows.forEach(([label, val], i) => {
  const fy = y + i * 22;
  doc.save().rect(50, fy, W, 20).fill(i % 2 === 0 ? WHITE : LIGHT).restore();
  doc.save().fontSize(8.5).fillColor(MUTED).font("Helvetica").text(label, 56, fy + 6).restore();
  doc.save().fontSize(9).fillColor(SLATE).font("Helvetica-Bold")
    .text(val, 50, fy + 5, { width: W, align: "right" }).restore();
});
y += finRows.length * 22 + 6;
rule(y);

// ══════════════════════════════════════════════════════════════════════════════
// PAGE 6 — FIFO COMPLIANCE
// ══════════════════════════════════════════════════════════════════════════════
doc.addPage();
y = pageHeader("FIFO Compliance Intelligence", "First-In-First-Out compliance matrix · All branches · May 2026");

y = sectionTitle("FIFO Compliance Matrix — All Branches (%)", y);
y = table(
  ["Department", "BR-01","BR-04","BR-09","BR-12","BR-15","Chain Avg","Status"],
  [
    ["Meat",       "89","94","78","83","81","85","ON TRACK"],
    ["Fish",       "82","88","71","76","74","78","AT RISK"],
    ["Bakery",     "85","91","80","84","82","84","ON TRACK"],
    ["Dairy",      "78","85","68","74","72","75","AT RISK"],
    ["Vegetables", "86","90","77","82","80","83","ON TRACK"],
    ["Shelf",      "92","96","87","91","89","91","ON TRACK"],
    ["Inventory",  "86","91","79","85","83","85","ON TRACK"],
  ],
  50, y, [94, 50, 50, 50, 50, 50, 64, 72]
);

y += 18;
y = sectionTitle("FIFO 30-Day Trend — Chain Average by Department", y);

// bar chart style trend
const trendData = [
  { dept: "Shelf",      vals: [88, 89, 90, 91, 91, 92, 91] },
  { dept: "Bakery",     vals: [80, 81, 83, 83, 84, 84, 84] },
  { dept: "Meat",       vals: [80, 82, 83, 84, 85, 85, 85] },
  { dept: "Vegetables", vals: [79, 80, 81, 82, 82, 83, 83] },
  { dept: "Inventory",  vals: [74, 77, 80, 82, 84, 85, 85] },
  { dept: "Fish",       vals: [72, 73, 74, 76, 77, 78, 78] },
  { dept: "Dairy",      vals: [68, 69, 71, 72, 74, 75, 75] },
];
const weeks = ["W1","W2","W3","W4","W5","W6","W7"];
const colWt = [95, 57, 57, 57, 57, 57, 57, 58];
// header row
doc.save().rect(50, y, W, 18).fill(BRAND).restore();
["Department",...weeks].forEach((h, i) => {
  doc.save().fontSize(7.5).fillColor(WHITE).font("Helvetica-Bold")
    .text(h, 50 + colWt.slice(0,i).reduce((a,b)=>a+b,0) + 5, y + 5, { width: colWt[i]-8, lineBreak: false }).restore();
});
y += 18;
trendData.forEach((row, ri) => {
  doc.save().rect(50, y, W, 20).fill(ri % 2 === 0 ? WHITE : LIGHT).restore();
  doc.save().fontSize(7.5).fillColor(MUTED).font("Helvetica").text(row.dept, 55, y + 6).restore();
  row.vals.forEach((v, vi) => {
    const vx = 50 + colWt.slice(0, vi+1).reduce((a,b)=>a+b,0) + 5;
    const col = v >= 85 ? GREEN : v >= 75 ? AMBER : RED;
    doc.save().fontSize(7.5).fillColor(col).font("Helvetica-Bold")
      .text(`${v}%`, vx, y + 6, { width: colWt[vi+1]-8, lineBreak: false }).restore();
  });
  doc.save().strokeColor(BORDER).lineWidth(0.3)
    .moveTo(50, y+20).lineTo(545, y+20).stroke().restore();
  y += 20;
});

y += 16;
// Insight callout
doc.save().roundedRect(50, y, W, 50, 6).fill("#EDE9FE").restore();
doc.save().rect(50, y, 4, 50).fill(BRAND).restore();
doc.save().fontSize(8).fillColor(BRAND).font("Helvetica-Bold").text("✦  FIFO COMPLIANCE INSIGHT", 62, y + 10).restore();
doc.save().fontSize(8).fillColor(SLATE).font("Helvetica")
  .text(
    "Dairy and Fish remain the two lowest-compliance departments across all branches. " +
    "Inventory dept showed the strongest recovery — up 11 points over the 7-week period following " +
    "AI-assigned morning rotation missions. Target for all departments: ≥ 90% by end of Q2.",
    62, y + 24, { width: W - 20, lineGap: 2 }
  ).restore();

// ══════════════════════════════════════════════════════════════════════════════
// PAGE 7 — PRODUCTIVITY RANKINGS
// ══════════════════════════════════════════════════════════════════════════════
doc.addPage();
y = pageHeader("Productivity Rankings", "Cross-branch department competition · May 2026 leaderboard");

y = sectionTitle("Cross-Branch Department Leaderboard — Top 15", y);
y = table(
  ["#", "Dept", "Branch", "Score", "FIFO", "Waste", "Bonus Pool", "Award"],
  [
    ["1",  "Meat",       "Branch 04", "91", "94%", "4.2%", "₼1,840", "GOLD"],
    ["2",  "Bakery",     "Branch 04", "87", "91%", "4.8%", "₼1,620", "SILVER"],
    ["3",  "Shelf",      "Branch 01", "84", "92%", "1.4%", "₼1,480", "BRONZE"],
    ["4",  "Bakery",     "Branch 01", "83", "85%", "6.0%", "₼1,350", "—"],
    ["5",  "Meat",       "Branch 01", "81", "89%", "4.2%", "₼1,280", "—"],
    ["6",  "Vegetables", "Branch 04", "79", "90%", "6.7%", "₼1,190", "—"],
    ["7",  "Inventory",  "Branch 01", "78", "91%", "2.6%", "₼1,140", "—"],
    ["8",  "Shelf",      "Branch 04", "77", "96%", "1.4%", "₼1,090", "—"],
    ["9",  "Dairy",      "Branch 04", "74", "85%", "5.9%", "₼980",   "—"],
    ["10", "Meat",       "Branch 12", "72", "83%", "6.3%", "₼940",   "—"],
    ["11", "Fish",       "Branch 04", "70", "88%", "6.4%", "₼880",   "—"],
    ["12", "Bakery",     "Branch 09", "66", "80%", "8.3%", "₼720",   "—"],
    ["13", "Fish",       "Branch 01", "62", "82%", "9.0%", "₼640",   "—"],
    ["14", "Dairy",      "Branch 09", "58", "68%", "9.1%", "₼540",   "—"],
    ["15", "Fish",       "Branch 09", "54", "71%","11.2%", "₼460",   "—"],
  ],
  50, y, [26, 76, 86, 42, 46, 52, 80, 72], 17
);

y += 16;
// Dept avg summary bars
y = sectionTitle("Average Productivity Score by Department", y);
const deptAvg = [
  { dept: "Meat",       avg: 79 },
  { dept: "Bakery",     avg: 78 },
  { dept: "Shelf",      avg: 77 },
  { dept: "Vegetables", avg: 73 },
  { dept: "Inventory",  avg: 72 },
  { dept: "Dairy",      avg: 64 },
  { dept: "Fish",       avg: 61 },
];
deptAvg.forEach((d) => {
  const col = d.avg >= 75 ? GREEN : d.avg >= 65 ? AMBER : RED;
  doc.save().fontSize(8.5).fillColor(SLATE).font("Helvetica-Bold").text(d.dept, 50, y).restore();
  progressBar(140, y + 2, 240, d.avg / 100, col);
  doc.save().fontSize(9).fillColor(col).font("Helvetica-Bold")
    .text(`${d.avg}/100`, 390, y).restore();
  y += 22;
});

// ══════════════════════════════════════════════════════════════════════════════
// PAGE 8 — MISSIONS
// ══════════════════════════════════════════════════════════════════════════════
doc.addPage();
y = pageHeader("AI Daily Missions", "Operational mission system · Week of 12–16 May 2026");

y = sectionTitle("Mission Completion Rate — All Departments", y);
y = table(
  ["Mission", "Departments", "Freq", "Completion", "Status"],
  [
    ["Morning FIFO Rotation Check",        "Meat, Fish, Dairy",   "Daily",     "92%", "ON TRACK"],
    ["Cold-chain Temperature Audit",       "Fish, Dairy",         "Daily",     "78%", "AT RISK"],
    ["End-of-Day Waste Logging",           "All Departments",     "Daily",     "96%", "ON TRACK"],
    ["Near-Expiry Product Clearance",      "Fish, Dairy, Meat",   "Daily",     "71%", "AT RISK"],
    ["Shelf Gap Replenishment < 10 min",   "Shelf",               "Hourly",    "88%", "ON TRACK"],
    ["Freshness Visual Check",             "Vegetables, Bakery",  "2× Daily",  "94%", "ON TRACK"],
    ["Inventory Cycle Count",              "Inventory",           "Weekly",    "83%", "ON TRACK"],
    ["Planogram Compliance Audit",         "Shelf",               "Weekly",    "97%", "ON TRACK"],
    ["Cross-dept Rotation Log Submission", "All Departments",     "Daily",     "68%", "AT RISK"],
  ],
  50, y, [186, 108, 56, 72, 73], 19
);

y += 18;
y = sectionTitle("AI Strategic Recommendations", y);

const recs = [
  {
    priority: "HIGH",
    color: RED,
    title: "Cold-Chain Intervention — Fish Dept (BR-09, BR-01, BR-15)",
    body: "Three branches are below the 90% cold-chain compliance threshold. Mandatory twice-daily temperature audit with manager sign-off required. Estimated waste reduction: ₼4,200/quarter.",
  },
  {
    priority: "HIGH",
    color: RED,
    title: "Near-Expiry Clearance Protocol — Dairy Dept (Chain-wide)",
    body: "Dairy near-expiry clearance at 67% vs 90% target. Implement AI-triggered markdown pricing at T-48h. Projected revenue recovery: ₼6,800/quarter.",
  },
  {
    priority: "MEDIUM",
    color: AMBER,
    title: "Cross-Branch Knowledge Transfer — Meat Dept (BR-04 → BR-09, BR-15)",
    body: "Branch 04 Meat outperforms chain average by 12 pts. Schedule structured workflow knowledge-share. Target: lift BR-09 & BR-15 by 8+ pts in Q3.",
  },
  {
    priority: "MEDIUM",
    color: AMBER,
    title: "FIFO Training Refresh — Dairy & Fish Depts",
    body: "FIFO compliance in Dairy (75%) and Fish (78%) is lowest chain-wide. Recommend 2-hour in-store refresher with hands-on rotation exercise. Target: 85% within 30 days.",
  },
];
recs.forEach((r) => {
  doc.save().roundedRect(50, y, W, 54, 6).fill(LIGHT).restore();
  doc.save().rect(50, y, 3, 54).fill(r.color).restore();
  const pw = doc.widthOfString(r.priority, { fontSize: 7 }) + 10;
  doc.save().roundedRect(60, y + 8, pw, 13, 4).fill(r.color + "22")
    .fontSize(7).fillColor(r.color).font("Helvetica-Bold")
    .text(r.priority, 65, y + 11, { lineBreak: false }).restore();
  doc.save().fontSize(8.5).fillColor(SLATE).font("Helvetica-Bold")
    .text(r.title, 60 + pw + 6, y + 8, { width: W - pw - 16 }).restore();
  doc.save().fontSize(7.5).fillColor(MUTED).font("Helvetica")
    .text(r.body, 60, y + 26, { width: W - 18, lineGap: 1.5 }).restore();
  y += 62;
});

// ══════════════════════════════════════════════════════════════════════════════
// PAGE 9 — APPENDIX
// ══════════════════════════════════════════════════════════════════════════════
doc.addPage();
y = pageHeader("Appendix & Methodology", "Data sources · Scoring formula · Glossary");

y = sectionTitle("Productivity Score Formula", y);
doc.save().roundedRect(50, y, W, 44, 6).fill(LIGHT).restore();
doc.save().fontSize(9).fillColor(BRAND).font("Helvetica-Bold")
  .text("Score = 0.30 × WasteReduction + 0.25 × FIFOCompliance + 0.20 × Turnover + 0.15 × TaskEfficiency + 0.10 × SalesGrowth",
    60, y + 8, { width: W - 20 }).restore();
doc.save().fontSize(7.5).fillColor(MUTED).font("Helvetica")
  .text("All components normalised 0–100. Weights calibrated against historical branch performance data.", 60, y + 28).restore();
y += 58;

y = sectionTitle("Data Sources", y);
y = table(
  ["Data Source", "System", "Refresh Cadence"],
  [
    ["Inventory Rotation Logs",  "POS + WMS integration",   "Real-time"],
    ["Cold-chain Temperature",   "IoT sensor network",      "Every 15 min"],
    ["FIFO Compliance Scans",    "Barcode scanner events",  "Per scan"],
    ["Staff Task Completion",    "Mobile app check-ins",    "Per event"],
    ["Spoilage Event Reports",   "Manager app entries",     "Per event"],
    ["Sales Velocity",           "POS transaction stream",  "Hourly"],
    ["Planogram Compliance",     "Image recognition (AI)",  "Daily audit"],
  ],
  50, y, [190, 190, 115]
);

y += 18;
y = sectionTitle("Glossary", y);
const glossary = [
  ["FIFO",               "First-In, First-Out — stock rotation principle ensuring oldest inventory is sold first."],
  ["Waste Rate",         "Percentage of received stock discarded due to spoilage, damage, or expiry."],
  ["Productivity Score", "Composite 0–100 score measuring department operational efficiency (see formula above)."],
  ["Cold-chain",         "Temperature-controlled supply and storage system for perishable goods."],
  ["Mission",            "AI-generated daily operational task assigned to a department to address a detected risk."],
  ["Cross-Branch",       "Ranking of same-category departments across all branches to drive performance."],
];
glossary.forEach(([term, def]) => {
  doc.save().fontSize(8.5).fillColor(SLATE).font("Helvetica-Bold").text(term, 50, y).restore();
  doc.save().fontSize(7.5).fillColor(MUTED).font("Helvetica").text(def, 140, y, { width: W - 90 }).restore();
  y += 22;
});

y += 8;
rule(y);
y += 14;
doc.save().fontSize(7.5).fillColor(MUTED).font("Helvetica")
  .text(
    "This report is generated automatically by the Bravo AI Workforce Intelligence engine. " +
    "All data is based on operational inputs from branch management systems and is accurate as of the report date. " +
    "For queries contact the Bravo AI platform team.",
    50, y, { width: W, align: "center", lineGap: 2 }
  ).restore();

// ── Page numbers (all pages) ──────────────────────────────────────────────────
const total = doc.bufferedPageRange().count;
for (let i = 0; i < total; i++) {
  doc.switchToPage(i);
  if (i === 0) continue; // no page number on cover
  doc.save().fontSize(7).fillColor(MUTED).font("Helvetica")
    .text(
      `Bravo AI Workforce Intelligence  ·  Confidential  ·  Page ${i + 1} of ${total}`,
      50, 822, { width: W, align: "center" }
    ).restore();
}

doc.end();
console.log(`✓ PDF written → ${OUT}  (${total} pages)`);
